---
firewall_pkg: firewalld
firewall_svc: firewalld
web_pkg: httpd
web_svc: httpd
ssl_pkg: mod_ssl

packages:
  - "{{ firewall_pkg }}"
  - "{{ web_pkg }}"
  - "{{ ssl_pkg }}"

services:
  - "{{ firewall_svc }}"
  - "{{ web_svc }}"
