---
# created the variables as defined in lab, but also the list variables
# "packages" and "services"; the lab variables aren't strictly needed here

web_pkg: httpd
firewall_pkg: firewalld
python_pkg: python3-PyMySQL

packages:
  - "{{ web_pkg }}"
  - "{{ firewall_pkg }}"
  - "{{ python_pkg }}"

web_service: httpd
firewall_service: firewalld

services:
  - "{{ web_service }}"
  - "{{ firewall_service }}"
