---
- name: Check httpd status
  hosts: webserver
  become: false
  gather_facts: false

  tasks:
    - name: check httpd status
      ansible.builtin.command:
        cmd: systemctl status httpd
      register: result

    - name: display httpd status
      ansible.builtin.debug:
        var: result
