---
- name: Task failure exercise
  hosts: databases
  become: true
  gather_facts: false
  vars_files:
    - vars/main.yml

  tasks:
    - name: "{{ web_package }} is present"
      ansible.builtin.dnf:
        name: "{{ web_package }}"
        state: present

    - name: "{{ db_package }} is present"
      ansible.builtin.dnf:
        name: "{{ db_package }}"
        state: present
