---
- name: Task failure exercise - step 10.1
  hosts: databases
  become: true
  gather_facts: false
  vars_files:
    - vars/main_8.2.yml

  tasks:
    - name: check local time
      ansible.builtin.command: date
      register: command_result
      changed_when: false

    - name: display the local time
      ansible.builtin.debug:
        var: command_result.stdout

    - name: attempt to set up webserver
      block:
        - name: "{{ web_package }} is present"
          ansible.builtin.dnf:
            name: "{{ web_package }}"
            state: present
          failed_when: web_package == "httpd"
      rescue:
        - name: "{{ db_package }} is present"
          ansible.builtin.dnf:
            name: "{{ db_package }}"
            state: present
      always:
        - name: "{{ db_service }} is started"
          ansible.builtin.service:
            name: "{{ db_service }}"
            state: started

