---
- name: Configure SOE
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - name: Configure /etc/motd
      ansible.builtin.template:
        src: files/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

