---
- name: Configure web server
  hosts: servera.lab.example.com
  become: true
  gather_facts: true
  vars_files:

  tasks:
    - name: import the environment
      ansible.builtin.import_tasks: tasks/environment.yml
      vars:
        package: httpd
        service: httpd

    - name: import the firewall
      ansible.builtin.import_tasks: tasks/firewall.yml
      vars:
        firewall_pkg: firewalld
        firewall_svc: firewalld
        rule:
          - http
          - https

    - name: import the placeholder
      ansible.builtin.import_tasks: tasks/placeholder.yml
      vars:
        file: /var/www/html/index.html

- ansible.builtin.import_playbook: plays/test.yml
  vars:
    url: http://servera.lab.example.com
