---
- name: Install simple agent package
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - vars/main.yml

  tasks:
    - name: gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: display package info for {{ custom_pkg }} package
      ansible.builtin.debug:
        var: ansible_facts.packages[custom_pkg]
      when: custom_pkg in ansible_facts.packages

    - name: example yum repo is configured
      ansible.builtin.yum_repository:
        name: example-internal
        file: example
        baseurl: http://materials.example.com/yum/repository
        gpgcheck: true
        description: Example Inc. Internal YUM repo
        state: present

    - name: example yum gpg key is installed
      ansible.builtin.rpm_key:
        key: http://materials.example.com/yum/repository/RPM-GPG-KEY-example
        state: present

    - name: "{{ custom_pkg }} is installed"
      ansible.builtin.dnf:
        name: "{{ custom_pkg }}"
        state: present

    - name: gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: display package info for {{ custom_pkg }} package
      ansible.builtin.debug:
        var: ansible_facts.packages[custom_pkg]
      when: custom_pkg in ansible_facts.packages
