---
- name: Add text to an existing file
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: add a single line of text to a file
      ansible.builtin.lineinfile:
        path: /home/devops/users.txt
        line: This line was added by the lineinfile module.
        state: present
